# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
