# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20171107_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='first_pic_url',
            field=models.URLField(null=True),
        ),
    ]
