# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_article_first_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_pic_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
